Paper info query: https://krr.triply.cc/annadg/-/queries/Paper-class-query/3
Provenance info query: https://krr.triply.cc/annadg/-/queries/Provence-objects-query/2
Hypothesis info query: https://krr.triply.cc/annadg/-/queries/Hypothesis-class-query/1
Blank Node info query: https://krr.triply.cc/annadg/-/queries/Blank-Node-query/2
Abstract data query (used for extracting hypothesis keywords): https://krr.triply.cc/annadg/-/queries/Abstract-Data-Query/1
